services:
  - type: web
    name: RESTAURENT-QR-ORDERING-
    runtime: node
    region: oregon
    plan: free
    healthCheckPath: /health
    rootDir: .
    buildCommand: npm install --prefix server && npm install --prefix client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://restaurant-qr-ordering.onrender.com/api/auth/google/callback
      - key: PAYMENT_PROVIDER
        value: mock
      - key: STORAGE_PROVIDER
        value: supabase
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        value: menu-images
      - key: CLIENT_URL
        value: https://restaurant-qr-ordering.onrender.com
      - key: SERVER_URL
        value: https://restaurant-qr-ordering.onrender.com
      - key: ALLOWED_ORIGINS
        sync: false
      - key: FORCE_HTTPS
        value: true
      - key: LOG_LEVEL
        value: info
